[package]
name = "themelio-vanity"
version = "0.1.0"
authors = ["nptr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tmelcrypt = "0.2.4"
base32 = "0.4.0"

[profile.release]
strip = true
